[tool.poetry]
name = "ml-adp"
version = "0.1.0"
description = ""
authors = ["Ruben Wiedemann <r.wiedemann@campus.lmu.de>"]

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.9.0"
numpy = "^1.21.2"
matplotlib = "^3.4.3"

[tool.poetry.dev-dependencies]
ipykernel = "^6.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
