[tool.poetry]
name = "ml-adp"
version = "0.2.1"
description = ""
authors = ["Ruben Wiedemann <r.wiedemann@campus.lmu.de>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
torch = "^1.9.0"
numpy = "^1.21.2"
matplotlib = "^3.4.3"
autoclasstoc = "^1.3.0"
ipykernel = {version = "^6.4.1", optional = true}

[tool.poetry.extras]
jupyter = ["ipykernel"]


[tool.poetry.dev-dependencies]
Sphinx = "^4.2.0"
sphinx-rtd-theme = "^0.5.2"
sphinx-math-dollar = "^1.2"
numpydoc = "^1.1.0"
sphinx-autodoc-typehints = "^1.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
